import type { Metadata } from "next";
// s

import { SessionProvider } from "next-auth/react";
import Menu from "../../components/navbar";
import Footer from "../../components/footer";
// import { auth } from "@/auth"; //sirve para traer los datos de la sesion cuando trabajo con server

export const metadata: Metadata = {
  title: "Mecanica Guemes",
  description: "Generated by create next app",
};
export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // una vez que funcione el login, podemos trabajar con auth
  //*************************************
  //   const session = await auth();
  //   const isAdmin = session?.user?.rol_usuario === "admin";
  //   const isVendedor = session?.user.rol_usuario === "residente";
  //   const isSeguridad = session?.user.rol_usuario === "seguridad";

  return (
    <div className={`min-h-screen flex flex-col `}>
      {/* <SessionProvider session={session}> */}
      {/* <SharedStateProvider> */}
      {/* {!(isAdmin || isVendedor) && <Menu />} */}

      <SessionProvider>
        <Menu />
        {/* El main crece para empujar al footer abajo */}
        <main className="flex-1">{children}</main>

        {/* {!(isAdmin || isVendedor) && <Footer />} */}
        <Footer />
        {/* </SharedStateProvider> */}
      </SessionProvider>
    </div>
  );
}
